### PR TITLE
Kolibri application enhancements

### PR DESCRIPTION
**Pull request by mrpau-richard**
## Kolibri application enhancements
- [x] Auto start Kolibri application during windows startup.
- [x] Automatically open the browser when the Kolibri server is running.
- [x] Auto start the server when the user double clicked the Kolibri icon.
- [x] Remove start and stop options at the system tray menu bar.

/cc @radinamatic @indirectlylit @laurenlichtman

### CODE REVIEW

**Comment by mrpau-richard** [comment]
@radinamatic here's the [windows installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMbVVhaVFSSm50Y2c) to test this PR.

**Comment by radinamatic** [comment]
Good work @mrpau-richard :+1: 

I'd suggest the following improvements:

1. If I uncheck the option "Run Kolibri on system start", it seems to behave correctly as the server does not start when I restart the machine. However, as soon as I start the server with the desktop shortcut and the server starts, this also seems to reactivate the option "Run Kolibri on system start". This should not happen, meaning that if the user intentionally deactivated it, we should wait for the user to intentionally activate it again, and not do it by default on each server start.

2. I'm concerned that even when the user **does** want the server to run on each system start, they might **not** want the browser to open each time. I'm wondering if we should add another option, something like "Open browser when Kolibri starts", checked by default upon install, but that would give users the option to uncheck it, if they prefer.
We rightfully implemented the automatic load in the browser for the less tech savvy and first-time users, but I'm thinking that once users become more familiar with how Kolibri works, they might find the option annoying. Thoughts @indirectlylit? 

3. Change the wording of this confirmation alert to `Are you sure you want to stop Kolibri?`

win7 start running - oracle vm virtualbox_427

4. Place the desktop shortcut by default - since the shortcut is now required to start the server, it should not be optional to install it (IMHO we should not even require input by the user and have it installed anyway).

We are still missing these from the [original issue](https://github.com/learningequality/kolibri-installer-windows/issues/23), but an excellent start! :slightly_smiling_face::

- [ ] If server doesn’t start within 5 seconds, a notification bubble `Kolibri is still starting, please wait...` appears. Repeat the notification every 5 seconds. 
- [ ] Show the notification bubble `Kolibri has stopped... You can restart it from the desktop shortcut.` when the server gets shut down by an external method (either crash or manual shutdown).

**Comment by indirectlylit** [comment]
hey sorry - I missed this PR. will review asap. thanks for the quick work!

**Comment by indirectlylit** [comment]
>  I'm wondering if we should add another option, something like "Open browser when Kolibri starts", checked by default upon install, but that would give users the option to uncheck it, if they prefer.

that seems reasonable to me

**Comment by mrpau-richard** [comment]
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by radinamatic** [comment]
Going the right direction, still a few things to solve:

1. **Desktop shortcut by default**: I still see the step in the installer where the user is invited to do this. Granted the checkbox is checked by default, but it is still active, and somebody could uncheck it. Could we simply skip this step, and place the shortcut **without** any input from the user?

2. This step is still present, when we agreed to make it **hidden from the user**: win10 start running - oracle vm virtualbox_449

3. The next step is still problematic since it lasts for a long time, and it gives the **impression that the installer is frozen**, as the green bar is full the whole time. 
win10 start running - oracle vm virtualbox_450

Do you have the means to make this green bar fill in gradually, so it does not seem stuck at this point? 

If not, is it at least possible to advance from this step and display a more prominent message for the user: ` Setup wizard is copying files. This may take a while, please wait...`. Maybe in bigger or bold font, so it's more visible...?

4. **Add the `Launch Kolibri` checkbox** activated by default on the final wizard window: 
pasted_image_at_2017_08_08_04_24_pm

5. Order of items in the task tray icon menu - no second level `Options`:
```
Load in browser
--------------------
Run Kolibri at system startup (checked by default)
Open browser when Kolibri starts (checked by default)
--------------------
Exit
```

**Comment by indirectlylit** [comment]
thanks for posting these notes @radinamatic 

@mrpau-richard it's looking great! With these additional changes we'll be golden.

**Comment by mrpau-richard** [comment]
@radinamatic I almost done on the task in this PR except the issue in when you launch the Kolibri executable after kolibri finished install. it will give you an error about KOLIBRI_SCRIPT_DIR not found, but if you directly double click the kolibri icon on desktop that error will not exist. 
I'm still fixing on that one. But you can start testing using this [windows installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMYkVMWFBLbjhva2M).

**Comment by radinamatic** [comment]
@mrpau-richard As you described, the `KOLIBRI_SCRIPT_DIR not found` appears after installation, and Kolibri is not launched automatically. If one wants to open it manually after the installation, it cannot be done by the option `Load in browser` as it is is grayed out, and Kolibri does not seem to be running:

w7 start running - oracle vm virtualbox_618

The only solution seems to be to use the option `Exit` and start from the desktop shortcut as you mention. 

The green bar with the alert has improved, and I am particularly happy with the looping of the notification bubble that informs the user that the server is starting, good job! :+1:

w7 start running - oracle vm virtualbox_615

Let's get this last error sorted out and we'll have a much more user friendly Windows Installer!!! :tada:

**Comment by radinamatic** [comment]
On another matter, the import channel feature was not working on this build:

w7 start running - oracle vm virtualbox_620

I also noticed that even though the version states 0.6xxxx, this build still packages the 0.5 release codebase. Since there is a `release-v0.6.x` branch and tag, could you start building the installer with it, so I can kill more birds with one stone...? Thanks! :slightly_smiling_face:

**Comment by mrpau-richard** [comment]
@radinamatic Here's the final [Windows installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMejZIZVNZS2dmVk0) for this PR. I already fixed the `KOLIBRI_SCRIPT_DIR` error. I also built that installer based in `release-v0.6.x` branch.

**Comment by radinamatic** [comment]
Awsome job @mrpau-richard! :+1: 

@indirectlylit I'd say all the proposed improvements have been implemented in this last installer. Can you test this yourself so we can merge? Word of advice, use the Windows 7 VM, it will be much faster - no need for both of us to waste time with Windows 10... :roll_eyes:

**Comment by mrpau-richard** [comment]
@radinamatic I think we need to merge this PR to test it in my ongoing PR's. Lets just create an issue if we found bug's during testing.

**Comment by radinamatic** [comment]
@indirectlylit I have no problem with approving this if you don't have time to test this on your end...?

**Comment by indirectlylit** [comment]
sorry for the _very_ long delay. This looks great - nice job @mrpau-richard !

**Pull request merged**
