### PR TITLE
Implement new translated strings from the Crowdin

### PR DESCRIPTION
**Pull request by mrpau-richard**
This is an initial update for the innosetup `isl` files need to double check if the strings are properly displayed at the setup wizard, I'm still working on updating the Kolibri GUI strings. 

Use this [installer](https://drive.google.com/file/d/1h6B-3ng-ENxOiYCyMn2rhoKeg0fFywuj/view?usp=sharing) to test this.

This PR also fix the merge conflict at the `master` branch.

### CODE REVIEW

**Comment by radinamatic** [comment]
I'm seeing some inconsistencies and maybe some strings not included in the PO file...? :thinking: 

**`Yes` & `No` buttons on both install and uninstall windows**
Win7 (new start)  Running  - Oracle VM VirtualBox_712

Win7 (new start)  Running  - Oracle VM VirtualBox_714

`Uninstall Status`; `Uninstall Kolibri`

Win7 (new start)  Running  - Oracle VM VirtualBox_716

Is it possible to have the installer pick up and open by default in the Windows UI language? Even when I set up the VM to display the UI in Telugu, Kolibri installer opens in English. Then when I select Telugu in the languages selector step, after Pyhton was installed, the rest of the steps were still in English, until some steps appear in Spanish (???) :confused: 

Windows 10 - UI in Telugu | Windows 10 - UI in Telugu
------------ | -------------
Win10 (ITA)  Running  - Oracle VM VirtualBox_722 | Win10 (ITA)  Running  - Oracle VM VirtualBox_724

random strings still show up in English when the installer is in Bengali

Windows 10 - UI in Bengali | Windows 10 - UI in Bengali
------------ | -------------
Win10 (ITA)  Running  - Oracle VM VirtualBox_725 | Win10 (ITA)  Running  - Oracle VM VirtualBox_728
Win10 (ITA)  Running  - Oracle VM VirtualBox_727 | Win10 (ITA)  Running  - Oracle VM VirtualBox_729

**Comment by mrpau-richard** [comment]
@radinamatic I have an update about this `Is it possible to have the installer pick up and open by default in the Windows UI language?` The installer will auto now detect the Windows UI language default by the user and will not display the `SelectLanguage` setup wizard. I tested it using `Spanish Latin America`. here's the installer to test my new changes https://drive.google.com/file/d/1uaCy1dUxPhRMQks9WE8f1ucx2OfvEpGA/view?usp=sharing 

I'll double check those strings that's not translated and add them into po files.

**Comment by radinamatic** [comment]
Thank you, @mrpau-richard!

I might not have been clear enough in my suggestion, and I apologize. Personally, I don't like when technology *chooses for me*, and I prefer to be *offered a choice*. Therefore, I would suggest that **we do not skip the language selection (and automatically select the language for the users)**, as they (for whatever reason) might actually prefer to run the installer in a different language than the one their OS' UI is by default (I do this all the time, and not only when I'm testing :wink:). 

What I wanted us to achieve is to have the **languages selector window display in the OS UI default language, with that one pre-selected in the drop down**. That would still allow users to change (should they desire to do so), or just continue the installation in their default language. Does that sound doable?

For the rest I tested the latest installer, language sector is skipped on both Windows 7 and 10, and after testing on several different Windows languages I found only one string that might be missing (``Exit Setup``):

Windows 10 - UI in Italian | Windows 7 - UI in Bengali
------------ | -------------
Win10 (ITA)  Running  - Oracle VM VirtualBox_731 | Win7 (new start)  Running  - Oracle VM VirtualBox_734

**Comment by mrpau-richard** [comment]
@radinamatic please test this [installer](https://drive.google.com/file/d/1tjKbvP7vsihjRwL73TEFruFt-MhmB9nT/view?usp=sharing) again, I have an update about showing the `language selection` on the first setup wizard and I also implemented new strings from Crowdin at the Kolibri application.

I have changes on these `po` files please upload them at the Crowdin. 
[kolibri-application.po](https://github.com/learningequality/kolibri-installer-windows/compare/develop...mrpau:feature/use-translated-strings-from-crowdin#diff-d8fb0af1f27bfaafdf61decd496cc6c2)
[innosetup.po](https://github.com/learningequality/kolibri-installer-windows/compare/develop...mrpau:feature/use-translated-strings-from-crowdin#diff-2526a1b2aa7eb7360eb542d3a63aaae9)

**Comment by radinamatic** [comment]
Excellent work, @mrpau-richard, just as we discussed yesterday! :+1: :100: 

Windows 7 - UI in Marathi | Windows 7 - UI in Brazilian Portuguese 
------------ | -------------
Selection_738 | Selection_739


Windows 10 - UI in Telugu | Windows 10 - UI in Urdu
------------ | -------------
Win10 (ITA)  Running  - Oracle VM VirtualBox_743 | Win10 (ITA)  Running  - Oracle VM VirtualBox_744


Unfortunately, it way too late to start introducing the new strings now as almost all the translations are already done. Please revert the PO files to the previous state (the one that is currently on Crowdin, and thus translated), as it has only one string actually missing (Exit Setup), and this new version leaves 3 more (important ones used for notifications) untranslated, and we cannot have them ready in time. We'll make this changes in the future releases.

**Comment by radinamatic** [comment]
Actually, I'm thinking that once you've reverted the strings, we might merge this, and you can start working on starting the setup wizard with a proper locale in a separate PR.

One last thing that might need fixing here is the list of languages:

1. I see 2 Bulgarian items in the language selector:

   Win10 (ITA)  Running  - Oracle VM VirtualBox_745


2. We probably want to delete the last two from the selector (we don't support Greek, and Hindi/Marathi is already present above)

   Win10 (ITA)  Running  - Oracle VM VirtualBox_746

**Comment by mrpau-richard** [comment]
@radinamatic I think let's just keep the updated `po` files and upload it in the next release. I have a [new installer](https://drive.google.com/file/d/1NfGGr7rvyuIh-FuDvk791jXqjyG2mnez/view?usp=sharing) here fixing the duplicate language and remove the Greek and Nepali language at the language selection.

**Comment by radinamatic** [comment]
@mrpau-richard 

**We cannot keep the strings as they are now, as these make an essential message (_visible every time Kolibri is started_) appear as untranslated in ALL languages.** It makes no sense to have everything else localized, but have this message on startup appear in English...

Kolibri-accessible-English


Please revert whatever you changed in these strings, so we can proceed.

**Comment by mrpau-richard** [comment]
@radinamatic here's the [new installer](https://drive.google.com/file/d/1mMxX1tD-kVkgFD7uH2HrTmUDxcyJOupR/view?usp=sharing) to test the untranslated strings at the Kolibri application.

I have a sample screenshot below
Capture

**Comment by radinamatic** [comment]
@mrpau-richard Perfect, I can now see those strings with proper translations (I checked just 5-6 languages, but that should suffice), thank you for reverting that! :+1: 

However, we seem to be missing Swahili and Chinese in the installer language selector, but their translations are fully present on Crowdin, please add them too. 

And before we merge this, could you re-download the translations for all the languages from Crowdin, as some of them had corrections and new additions these past few days. Thank you!

**Comment by radinamatic** [comment]
@mrpau-richard Khmer is also missing from the installer language selector, please add it too!

**Comment by mrpau-richard** [comment]
@radinamatic new installer uploaded [here](https://drive.google.com/file/d/1rTG_f57nsmtkaj6b5gk9sgu5PvjzDfEi/view?usp=sharing) with updated translation strings from the Crowdin I also added the missing languages you mention above.

**Comment by mrpau-richard** [comment]
@radina this is how to get the Language code ([LCID](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/70feba9f-294e-491e-b6eb-56532684c37f)) to use in the Windows installer.

REF: https://stackoverflow.com/a/57700172
In the command prompt run this command `reg query "HKEY_CURRENT_USER\Keyboard Layout\Preload"` this will load all the language code Id's installed in the Windows UI. 

I have a sample below using Spanish, Latin America. the active language code id always aligned at the 1 last code and the `580A` I used [here](https://github.com/mrpau/kolibri-installer-windows/blob/cc534a75699b0e3ef7fb6b418768b768109b86e5/src/inno-compiler/Languages/Spanish_Latin_America.isl#L15) to detect the language at the Kolibri Windows installer 

Captura

This is the [language code id](https://github.com/mrpau/kolibri-installer-windows/blob/cc534a75699b0e3ef7fb6b418768b768109b86e5/src/inno-compiler/Languages/Swahili_Tanzania.isl#L15) I use in the `Swahili, Tanzania`. I get it at the downloadable PDF here https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/70feba9f-294e-491e-b6eb-56532684c37f

**Comment by radinamatic** [comment]
@mrpau-richard The reason why the above is not working correctly is because that registry key is picking up the **currently set up keyboard(s)**, and there could be many (I have 5 on my personal Windows laptop :smiling_imp:, and 2 on this VM), which is different from the **(preferred) UI display language** (of which the user can have only one set up). 

This is why below the key you are using is giving you values for EN & ES, while the user set up UI language is Swahili:

Win7 (new start)  Running  - Oracle VM VirtualBox_788

So instead of `reg query "HKEY_CURRENT_USER\Keyboard Layout\Preload"`, **you should use `reg query "HKCU\Control Panel\Desktop" /v PreferredUILanguages`.**

Remember to grab the latest from Crowdin for Khmer and French, as there have been some changes in the strings since last week.

**Comment by radinamatic** [comment]
Yes, this final installer is working very well on Windows 7, and correctly picking up all the locales! :+1: 

I'm going to confirm on Windows 10, and then we should be good to go :slightly_smiling_face:

**Comment by indirectlylit** [comment]
great! let's get this merged in and upgrade 0.14 to point at it

**Comment by radinamatic** [comment]
Wonderful!!! :boom: 

Windows 10 - UI in Swahili | Windows 10 - UI in Telugu | Windows 10 in Vietnamese 
------------ | ------------- | -------------
Win10 (all-languages)  Running  - Oracle VM VirtualBox_791 | Win10 (all-languages)  Running  - Oracle VM VirtualBox_792 | Win10 (all-languages)  Running  - Oracle VM VirtualBox_793

**Comment by mrpau-richard** [comment]
>Looks great on both Windows 7 & 10, merge away! 

Thanks, merging this.

**Pull request merged**
