### PR TITLE
Uninstall kolibri static when uninstalling kolibri.

### LINKED ISSUE #15: Uninstalling Kolibri on Windows doesn't uninstall kolibri-static
This issue is already fixed in [KA Lite Windows installer](https://github.com/learningequality/ka-lite-installers/issues/387) and will also apply the fix in Kolibrri Windows installer.

### PR DESCRIPTION
**Pull request by mrpau-richard**
## Summary 
I created a script to uninstall kolibri static during uninstallation.

## Issue addressed  
This fixes #15 

##

Here's the [windows installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMMklsYmVuR1FCU0U) to test this PR.

/cc @radinamatic @mrpau-eduard

### CODE REVIEW

**Comment by mrpau-eduard** [comment]
@mrpau-richard done reviewing your `PR` and test the installer.
Its working. It can be merge.

**Comment by mrpau-eduard** [comment]
Hi @radinamatic can you test the installer also if it is working on your side.

**Comment by radinamatic** [comment]
Hi @mrpau-eduard, Kolibri was successfully removed with installer, but we are missing the `Uninstall Kolibri` option from the Start menu... 😛 

uninstall-kolibri

So unless we want users to have to hunt down the uninstaller manually, we better put that option in the Start menu 😉 

Another thing just came to mind: since the uninstall process does not touch the `./kolibri` folder, and that in itself is Ok, maybe we should advise the user that all the content channels they downloaded (and those might be very big) are still present, just in case they want to wipe all Kolibri traces from that particular device to free some space on HD.

**Comment by mrpau-eduard** [comment]
@mrpau-richard  are we done on this one?

**Comment by mrpau-richard** [comment]
@radinamatic I think it's the same behaviour with kalite the uninstall kalite option is not available also in Windows 10. I think we can create another issue for that. And merge this PR to fix this [issue](https://github.com/learningequality/kolibri-installer-windows/issues/18#issuecomment-314585009)

screen shot 2017-06-30 at 3 29 53 pm
.

**Comment by radinamatic** [comment]
Working well on Win 7, will test 10 next! :+1: 

win7 start running - oracle vm virtualbox_346

**Pull request merged**
