### PR TITLE
Fix infinite server is starting notification

### LINKED ISSUE #113: Infinite "server is starting" notification
When I set the `KOLIBRI_HTTP_PORT` environment variable with non numeric characters and I run the Kolibri GUI, it will have an infinite `the server is starting` notification.

This also happened when a `port 8080` is occupied or not available.

### PR DESCRIPTION
**Pull request by mrpau-richard**
This will fix the Infinite "server is starting" notification when the kolibri server port is not available.

This fixes #113

### CODE REVIEW

**Comment by indirectlylit** [comment]
would you mind posting screenshots of what happens when there is an error while starting the server?

**Comment by mrpau-richard** [comment]
@indirectlylit here's the sample screenshot when Kolibri failed to start.
Screen Shot 2019-08-16 at 4 50 10 PM

**Comment by indirectlylit** [comment]
That looks good to me! Does the message remain visible until it's dismissed?

**Comment by mrpau-richard** [comment]
> That looks good to me! Does the message remain visible until it's dismissed?

The message will still visible on Windows 10 notifications list until the user clear it, But on Windows 7 that functionality is not available.

**Comment by mrpau-richard** [comment]
@indirectlylit I used `message box` to display the message, this is to surely notify the user that kolibri failed to start and it's also applicable to Windows 10 and 7. I have the sample screenshot below.
Screen Shot 2019-08-19 at 5 05 31 PM

**Comment by benjaoming** [comment]
The message box seems like a safer choice? When Kolibri doesn't start, a "discreet" or "stylish" notification UI shouldn't be preferable over a visible message box?

We could use the notification dialogues for other cases where messages do not entail failure or crashes.

**Comment by indirectlylit** [comment]
sounds good - let's go with the message box

**Comment by mrpau-richard** [comment]
Thanks for your feedback guys, I uploaded the installer [here](https://drive.google.com/open?id=1-mv9gKVqWcOYoSPHnoKS9HBTfkgaG3MP) to test it.

I have this steps to test this:
* Assuming that the Python is already installed in the machine.
* And run this command to occupied the kolibri default port(`python.exe -m http.server 8080`) sample screenshot below.
Screen Shot 2019-08-20 at 6 01 55 PM
* install the Kolibri Installer.
* Then run the Kolibri GUI and expect the message box showing that kolibri failed to start.

**Comment by mrpau-julius** [comment]
@mrpau-richard I'm done testing your PR on Windows 7, 8 and 10. The message box will appear if the `HTTP port 8080`  is used already or `KOLIBRI_HTTP_PORT` assign value is variable, which is a good thing.

as I observed the `GUI` is still running even if the Kolibri server is already stopped. The `GUI` must exit if the error occurs.

GUI_still_running

**Comment by mrpau-richard** [comment]
Thanks @mrpau-julius, I also implemented your suggestion to exit the `Kolibri GUI` when the server can't start. [here](https://drive.google.com/open?id=1MLjgQg5D4jdSU1JBc87OepWl1M24lFMU) is the new installer to test it.

**Comment by mrpau-julius** [comment]
That's great @mrpau-richard, the new installer looks good to me. 👍

**Comment by mrpau-richard** [comment]
> That's great @mrpau-richard, the new installer looks good to me. 

Thanks, merging this.

**Pull request merged**
