### PR TITLE
Update the uninstall script 

### LINKED ISSUE #21: Update the uninstall script
We are already using InnoSetup (with GUI to uninstall Kolibri on Windows).  Let us update the uninstall script for these tasks:

- [x] Confirming from the user whether to remove (or not) the Kolibri data folder
- [x] Removing the environment variables
- [x] Show dialogs and texts based on the [Google Doc - Kolibri uninstall text](https://docs.google.com/document/d/1XF2c0GVHUN9pxpxLq8f6XHk8CLclnVGTXqB3JgRtLLE/)
- [ ] On error, show the `TaskDialogMsgBox()` with the traceback

Good to have (?)

- [ ] Internationalization support for the texts

References:
* https://github.com/learningequality/kolibri-installer-windows/blob/develop/windows/installer-source/KolibriSetupScript.iss
* https://github.com/learningequality/kolibri-installer-windows/blob/develop/windows/scripts/uninstall-kolibri.bat

Original Text:

~~Create uninstall script that will clean environment variables and installed files during uninstallation. It must have the same functionality at [kalite-remover.sh](https://github.com/learningequality/ka-lite-installers/blob/master/osx/ka-lite-remover.sh)~~

### PR DESCRIPTION
**Pull request by mrpau-richard**
I added a confirmation message to delete the Kolibri data files during the uninstall process.

These are the sample images of the confirmation message box after I clicked the `kolibri uninstall`.
Screen Shot 2019-07-11 at 4 39 43 PM

Screen Shot 2019-07-11 at 4 40 11 PM

To test this [here](https://drive.google.com/open?id=11-1rd0ya1RdCiUjPr6Ye6xWtU2L7sMGh) is the installer.

This is still a work in progress PR.

This fixes #21

### CODE REVIEW

**Comment by indirectlylit** [comment]
Let's finalize the text using this doc: 

https://docs.google.com/document/d/1XF2c0GVHUN9pxpxLq8f6XHk8CLclnVGTXqB3JgRtLLE/edit#

**Comment by indirectlylit** [comment]
one other note is that we want to make that we can display error messages if the uninstall process fails

**Comment by mrpau-richard** [comment]
Updates: I was successfully implemented the `prompt 1 & 2` and `final message` describe in this [doc](https://docs.google.com/document/d/1XF2c0GVHUN9pxpxLq8f6XHk8CLclnVGTXqB3JgRtLLE/edit#)

The only issue is, the `Exit` button name is not available in the [MsgBox](http://www.jrsoftware.org/ishelp/index.php?topic=isxfunc_msgbox), And it will take more time if we use the `TaskDialogMsgBox()` for the custom button name.

These are the sample images of the  `prompt 1 & 2` and `final message`
Screen Shot 2019-07-12 at 5 24 57 PM

Screen Shot 2019-07-12 at 4 49 37 PM
Screen Shot 2019-07-12 at 5 28 48 PM


For the `error message` prompt, I think It will also consume more time to implement it. I need to read more about how to handle and fetch the error logs during uninstallation failed.



Here's the new installer to test this https://drive.google.com/open?id=1byI6Sj21Y5ffj5PXUzECaUQvJgouE9m0

**Comment by indirectlylit** [comment]
That looks great!

> The only issue is, the Exit button name is not available in the MsgBox, And it will take more time if we use the TaskDialogMsgBox() for the custom button name.

That's fine - let's stick with 'OK'

> For the error message prompt, I think It will also consume more time to implement it. I need to read more about how to handle and fetch the error logs during uninstallation failed.

Could you simulate an error and see what happens so we know the current behavior?

We mainly want to avoid a repeat of #94. The key is to ensure that there is some way for the user to know when something went wrong, and to find (manually if necessary) any error messages.

**Comment by cpauya** [comment]
To enable InnoSetup logging during uninstall, append the `/LOG` or `/LOG=<path to log file>` at the `unins???.exe`.  

* Example: `"C:\Program Files (x86)\Kolibri\unins000.exe" /LOG=c:\kolibri-uninstall.log`.  
* Reference: http://www.jrsoftware.org/ishelp/topic_uninstcmdline.htm

I've simulated these two situations during uninstall to see the log results:

| Action | Result | Notes | Log file |
|--|--|--|--|
| Renamed `pip*.exe` to `xpip*.exe`| Uninstall completed | Log file did not show any error | [kolibri-uninstall--missing pip.exe.log](https://github.com/learningequality/kolibri-installer-windows/files/3391058/kolibri-uninstall--missing.pip.exe.log) |
| Renamed `.kolibri/` folder into `x.kolibri/` | Uninstall completed (took about 3x longer) | Log file showed failure to delete directory and retried many times | [kolibri-uninstall--missing kolibri data folder.log](https://github.com/learningequality/kolibri-installer-windows/files/3391061/kolibri-uninstall--missing.kolibri.data.folder.log) |

I haven't found a way to programmatically do this in the InnoSetup script file yet.  The only feasible  way (and fastest to include this in [v1.3.1](https://github.com/learningequality/kolibri-installer-windows/milestone/7)) is to create a shortcut in Windows to the `unins???.exe` passing the `/LOG` argument, then have that link notified, shown to the user, or documented in our docs.

**Comment by radinamatic** [comment]
Testing this on Windows 7, so far so good: straight up uninstall procedure (when not trying to provoke any errors) went smooth, and even when I deleted the `.kolibri` folder, the uninstall procedure lasted only 1 minute. The `C:\Program Files\Kolibri` is still there, even though all the subfolders are empty:

Selection_151

**Comment by indirectlylit** [comment]
Awesome, thanks. Let's add the `/LOG` option and update the user documentation on how they kind find that file.

Also just a heads-up that @radinamatic  made a few edits to the text: https://docs.google.com/document/d/1XF2c0GVHUN9pxpxLq8f6XHk8CLclnVGTXqB3JgRtLLE/edit

**Comment by radinamatic** [comment]
>  heads-up that @radinamatic made a few edits to the text

Yes, still mulling on that, I'll ping you when I'm satisfied with the wording!

**Comment by radinamatic** [comment]
@mrpau-dev So few differences I noticed after testing on both Win7 and Win10:

1. `C:\Program Files\Kolibri` folder is not deleted on Win 7 but deleted correctly on Win 10.
2. There is no `Uninstall` option among the Kolibri Start menu folder in Win 10, but it is there in Win 7:

Win10 (Uninstall-script)  Running  - Oracle VM VirtualBox_152

Not hugely important, but some other programs (Oracle VBox and Python too) have it, so I'm just mentioning it for the reference.

3. Given the above, the only option to uninstall Kolibri on Win 10 seems to be through the **Settings > Apps > Uninstall**. During that process there is a visible reference to the `unins000.exe` file in the notification window, which does not look very appealing. Could we maybe rename that file to something like `kolibri_uninstall.exe` or similar?

win10

**Comment by radinamatic** [comment]
@mrpau-dev I've added some suggestions for the [uninstall wording in the doc](https://docs.google.com/document/d/1XF2c0GVHUN9pxpxLq8f6XHk8CLclnVGTXqB3JgRtLLE/edit#). 

Please include them in the next build.

**Comment by cpauya** [comment]
Thanks much for testing @radinamatic - but I'm afraid we can't further customise the texts on the uninstall dialog for now (set font to bold, colors, etc) because that would entail more work.

I will add those in the subsequent issue to be created re "error logging during uninstall".

**Comment by radinamatic** [comment]
Sounds good, @mrpau-dev! Please create the follow-up issues for the changes mentioned here that will not be included in the 1.3.1 milestone, so we can merge this and start the integration testing.

**Comment by cpauya** [comment]
Hi @radinamatic - regarding:

> `C:\Program Files\Kolibri` folder is not deleted on Win 7 but deleted correctly on Win 10.

I noticed that when Explorer has that folder open when doing the uninstallation, it won't be deleted in Win 10.  I wonder if it was the case when you tested in Win 7?

I have created a new issue for the enhancements/fixes at [Customize the Kolibri uninstaller.](https://github.com/learningequality/kolibri-installer-windows/issues/118).

I have these fixes for this PR, please see the attached screenshots:
1. Update the Uninstaller dialog texts based on the [uninstall text at Google Docs](https://docs.google.com/document/d/1XF2c0GVHUN9pxpxLq8f6XHk8CLclnVGTXqB3JgRtLLE/edit#).  VirtualBox_Win10a_16_07_2019_21_48_43

1. Add `Uninstall Kolibri` link at the Kolibri Start Menu folder (this image is under Windows 10).  VirtualBox_Win10a_16_07_2019_21_45_36

1. Add `/LOG=<desktop-location>\kolibri-uninstall.log` to the `uninst???.exe` for uninstaller logging.  VirtualBox_Win10a_16_07_2019_21_49_20

I'm currently rebuilding on BuildKite so will ping you when it's ready for testing.

**Pull request merged**
