### PR TITLE
Update built in Python installer from 2.7.13 into 3.4.3

### LINKED ISSUE #67: Change to Python 3?
I'm sure we've talked about this before: The built installer for Windows should not be based on Python 2.7

Here's an indirect consequence: https://github.com/learningequality/ka-lite-installers/pull/476

It seems that the issue is about using the .whl file built on Buildkite, but that file is now Python 3 compatible: https://github.com/learningequality/kolibri-installer-windows/pull/4

Could we target 0.10 for doing Python 3 on Windows?

### PR DESCRIPTION
**Pull request by mrpau-richard**
This fixes #67, [#5571](https://github.com/learningequality/ka-lite-installers/issues/475) and [#66](https://github.com/learningequality/kolibri-installer-windows/issues/66)

Here's the [installer](https://drive.google.com/open?id=1iTrBTWLJlaqG84hgCkNvwvKtCt86GmH7) to test this.

cc @radinamatic @benjaoming @indirectlylit

### CODE REVIEW

**Comment by benjaoming** [comment]
What is the reason for using 3.4.3 and not the latest 3.6.x?

**Comment by mrpau-richard** [comment]
@benjaoming the reason why I didn't use the latest release, is because Python 3.5+ don't have `msi` Windows installer release.

Python Windows release notes at the [3.5.0a2](https://www.python.org/downloads/release/python-350a2/) and up.
`Windows users:` If installing Python 3.5.0a2 as a non-privileged user, you may need to escalate to administrator privileges to install an update to your C runtime libraries.

**Comment by benjaoming** [comment]
> When I try to use the exe installer, I have this C runtime issue when installing the Python path at the root path.

Thanks! For now, it's great that we are going back to Python 3, just wanted the explanation for the record.

I think we should open an issue about this, the installer should be able to work with a Python environment installed anywhere.

**Comment by benjaoming** [comment]
@radinamatic would you be able to provide feedback here?

**Comment by radinamatic** [comment]
Installation working OK on Windows 10, the only thing seems to be some character encoding, but that can't be Python issue:

win10 start running - oracle vm virtualbox_151

win10 start running - oracle vm virtualbox_152

Happens with Kolibri UI in both English and Spanish, and equally on Firefox and Chrome.
@indirectlylit Not sure who to ping for this issue... :question:

**Comment by radinamatic** [comment]
@indirectlylit Trying to reproduce the issue with the newer installers, but coming up empty... Will investigate more!

**Pull request merged**
