### PR TITLE
windows installer can take a very long time during final step

### LINKED ISSUE #52: windows installer can take a very long time during final step
Some recent reports from windows 10:

* 40 minutes inside a VM (@radinamatic)
* 10 minutes on a fast windows laptop (@alanchenz)

This is in the final stage when the green bar is at 100%, so it can look to the end-user like things are totally frozen unless they're savvy enough to check the task manager.

Furthermore, by this point the desktop 'Kolibri' icon has already been created and the user can try starting the server. If/when they do this, they get a 'server is already running' error.

### PR DESCRIPTION
**Pull request by mrpau-richard**
This fixes #52 

I updated the progress bar from full green bar to marquee.
Prevent Kolibri GUI to run during the Kolibri installation.

temp

When the user click the kolibri icon and there is an existing Kolibri installation.
screen shot 2017-12-11 at 2 55 05 pm

@radinamatic you can grab the installer [here](https://drive.google.com/open?id=1FeL2s5G85FNBifqyjNLNyYmYx-MAea3a) to test this.

### CODE REVIEW

**Comment by indirectlylit** [comment]
nice1

**Comment by radinamatic** [comment]
That is so cool @mrpau-richard! 😍 

I cannot see the strings in the code, but I propose the following changes here:

in-progress

Alert title: 
`Installation in progress`

Alert message: 
`Kolibri installation is in progress. Please wait for the installer to finish, and Kolibri will open in your default browser.`

**Comment by mrpau-richard** [comment]
@radinamatic Thanks for reviewing this.
 I'll also update the Crowdin for the string translation.

**Comment by mrpau-richard** [comment]
@radinamatic I updated the Crowdin for the new strings translation.
Here's the newly built [installer](https://drive.google.com/open?id=1cUpdQxxK1GymWFRjJ1YUv-jSjQ6kd2w8), to test this PR again.

**Comment by radinamatic** [comment]
Looks perfect @mrpau-richard ! 👍 

win10 start running - oracle vm virtualbox_145

Really happy how this Windows installer is turning out... ❤️

**Comment by radinamatic** [comment]
I also updated the translations of the [installer and taskbar options on Crowdin](https://crowdin.com/project/kolibri-windows/es-ES#), those will be included by default on future builds, correct?

**Comment by mrpau-richard** [comment]
@radinamatic not yet, I'll need to update the Kolibri GUI, for those strings that you translated at Crowdin. To include it in the future build. And don't merge this PR yet until I fix the conflicts and commit the new translated strings from the Crowdin.

**Comment by radinamatic** [comment]
Gotcha, do your resolving thing, I was just eager to see the final result... 😊

**Comment by mrpau-richard** [comment]
@radinamatic here's the newly built [Windows installer](https://drive.google.com/open?id=1i-N7Pjjdwrkqc6St2Z7nv6a09p2LG2n6) for this PR. It contains the changes from the develop branch and the new translated strings from Crowdin.

**Comment by radinamatic** [comment]
Thanks @mrpau-richard, will test asap! 👍

**Comment by radinamatic** [comment]
@mrpau-richard 
I actually tested this last week, but failed to post the reply... 🤦‍♀️ 

Anyways, everything seems in order with the changes, just the language selection for the setup wizard is not working... 🤔 

I'm guessing that is not due to this PR but you are building with the old code, since that issue was fixed in 0.7 release, correct?

**Comment by mrpau-richard** [comment]
@radinamatic your right, that installer is built with the old code of Kolibri.

**Comment by indirectlylit** [comment]
awesome, thank you!

**Pull request merged**
