### PR TITLE
spanish translations for uninstaller

### PR DESCRIPTION
**Pull request by indirectlylit**
committed using windows endlines and Windows-1252 encoding

### CODE REVIEW

**Comment by indirectlylit** [comment]
merging hotfix

**Comment by indirectlylit** [comment]
* follow-up from #124
* refs #122

**Comment by benjaoming** [comment]
This was not released, unfortunately, as it went into `master` and then `develop` was tagged with 1.3.3 without a merge.

@mrpau-richard @indirectlylit just a heads up.

I will propose merging develop into master and creating a 1.3.4 release. The 1.3.3 is already out, so re-tagging is out of the question.

**Comment by indirectlylit** [comment]
@benjaoming is correct.

Releases should always be tagged on the `master` branch, never on the `develop` branch.

**Comment by cpauya** [comment]
Ouch! Thanks much for catching this @benjaoming - we must release a v1.3.4 ASAP @mrpau-richard

**Comment by mrpau-richard** [comment]
Okay @cpauya, I'll also update the steps to create a releases [here](https://github.com/learningequality/kolibri-installer-windows#steps-for-making-windows-installer-releases)

**Comment by benjaoming** [comment]
Thanks for following up with the release and the instructions up date @mrpau-richard and @mrpau-julius :+1:

**Pull request merged**
