### PR TITLE
Update the strings in the Windows installer po file

### PR DESCRIPTION
**Pull request by mrpau-richard**
I updated the strings in the installer po file.

cc @radinamatic

### CODE REVIEW

**Comment by radinamatic** [comment]
From https://github.com/learningequality/kolibri-installer-windows/issues/164#issuecomment-620771648

>>     include only the strings that appear in 5-6 steps visible in the default installation.
> ...
> Agreed that if possible, we should identify the strings we actually need and systematically get just those translated.

@mrpau-dev @mrpau-richard Would it be possible to achieve the above in the scope of this PR, or you prefer this to be merged first?

The goal is to filter the strings so the PO file contains only our custom ones, plus those that appear in the installer default 5-6 windows/steps.

**Comment by cpauya** [comment]
Agree @radinamatic - We will modify the PO file here to contain only our customized strings (including those in the installer UI wizard).

**Comment by benjaoming** [comment]
> Agreed that if possible, we should identify the strings we actually need and systematically get just those translated.

Suggestion: If we use a blacklist (list of all the strings to ignore), we won't have to remember to update a separate whitelist (a whitelist would also mean that "extracting" something from the .isl becomes largely meaningless).

**Comment by mrpau-richard** [comment]
@radinamatic I modify the po file to just translate those strings that we customised in the isl file. I think this PR is ready to merge and upload the installer po at Crowdin

**Comment by radinamatic** [comment]
>  our custom ones, **plus those that appear in the installer default 5-6 windows/steps**.

@mrpau-richard You've been a bit overzealous in slashing out those strings, and left out everything BUT those that we customized  :joy: 

Remember that ALL the strings that appear in Setup Wizard installation steps need to be translated in [22 languages we currently support in Kolibri](https://github.com/learningequality/kolibri/blob/develop/kolibri/locale/language_info.json) (plus Chinese), and not all of them appear to be available in the InnoSetup according to its own language selector: 

Selection_465

Changes to be implemented include, for example: eliminate Greek (that we do not support at the moment), change PT-PT for PT-BR, and include all the rest of the supported ones indicated in [`language_info.json`](https://github.com/learningequality/kolibri/blob/develop/kolibri/locale/language_info.json). 

I'm including a version of PO file with what I believe covers all the strings that we should aim to make available for translation: [kolibri-installer.po.zip](https://github.com/learningequality/kolibri-installer-windows/files/4573203/kolibri-installer.po.zip)

cc @cpauya

**Comment by benjaoming** [comment]
As suggested in the meeting:

Customized strings in the installer are written to `src/installer-and-application-po-files/kolibri-installer.po` (what this PR does).

The remaining standard InnoSetup strings could be extracted to a separate file so they can be translated only for the languages necessary? `src/installer-and-application-po-files/innosetup.po` ?

**Comment by mrpau-richard** [comment]
@radinamatic I created another po file for the InnoSetup strings as @benjaoming suggested comment above.

**Comment by benjaoming** [comment]
@radinamatic does this fix #150 ?

**Comment by benjaoming** [comment]
Does this fix #148 once the .po file has been pushed?

**Comment by radinamatic** [comment]
>  does this fix #150 ?

Hopefully it will, once the translations are in :wink: 

> Does this fix #148 once the .po files have been pushed?

To my understanding it will.
Switching the conversation there, since this is merged

**Pull request merged**
