### PR TITLE
Could not find pip.exe

### LINKED ISSUE #31: Could not find pip.exe
I'm not sure what led to this, but here are the steps I went through:

* Loaded up an old VM that had an old version of Kolibri installed
* Uninstalled Kolibri
* Ran the new installer

I saw this message

image

Clicking 'OK' there let me to a file chooser where presumably I was supposed to find pip.exe.

I clicked cancel, and then the installer seemed to continue and claimed to have succeeded.

Two high-level issues:

* Any ideas how it got into a state where it couldn't find pip, and how this might be prevented?
* If for some reason something goes wrong, the whole installer should just fail (with a helpful message) and quit if possible. We shouldn't be asking the user to find and select a system executable.

----

Note - I was using the installer linked from [this comment](https://github.com/learningequality/kolibri-installer-windows/pull/24#issuecomment-320200547).

### PR DESCRIPTION
**Pull request by mrpau-richard**
## Summary 
The installation must be failed if the installer not successfully install the Kolibri.
@radinamatic If the installer failed during the installation it will show a message box and uninstall the extracted files.
screen shot 2017-10-12 at 5 36 14 pm

To test this rename the `pip.exe` at the `Python27/Scripts` folder then run this [installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMRFFhZ2J6V0JpWHM)

FYI: Merged this [PR](https://github.com/learningequality/kolibri-installer-windows/pull/24) first before merging this.

## Issue addressed 
This fixes #31 

cc\ @radinamatic @indirectlylit

### CODE REVIEW

**Comment by indirectlylit** [comment]
hey @mrpau-richard - I merged #24 but now there's a conflict with this (and the other) open PRs

**Comment by indirectlylit** [comment]
resolved: https://github.com/mrpau/kolibri-installer-windows/commit/0a833aa3769f6475f5fede3f2acabcb25a93c919

**Comment by indirectlylit** [comment]
works well!

**Comment by mrpau-richard** [comment]
Hi @indirectlylit I'll try to resolve those conflict in my PR's and I'll ping you after that.

Thanks for testing this.

**Pull request merged**
