### PR TITLE
Add a setup logging and enhance the error messages

### PR DESCRIPTION
**Pull request by mrpau-julius**
Create a setup logging to catch when errors exist and enhance the error message in a proper way.

This are the examples of error when occurred:
errmsg1
errmsg2

Sample logs: [Kolibri-setup.log](https://github.com/learningequality/kolibri-installer-windows/files/3206201/Kolibri-setup.log)

### References
#94

### CODE REVIEW

**Comment by benjaoming** [comment]
Hi @mrpau-julius - great work. A comment on the text of the error dialog: Could you change the latter part to:

```
Something went wrong in the Kolibri installation. Please refer to the following log file for details: <path to file>

To get help, please visit our community forums: https://community.learningequality.org

Error details:
<name of exception, traceback etc>
```

**Comment by indirectlylit** [comment]
Hi - note I edited @benjaoming's comment above with slightly different copy.

If possible: 

* maintain formatting
* math and exception should be selectable so it's easy to copy to the clipboard
* the URL should be a link or selectable

**Comment by benjaoming** [comment]
@indirectlylit aren't such error prompts text-only usually?

**Comment by indirectlylit** [comment]
It looks like [it's possible](http://www.jrsoftware.org/ishelp/index.php?topic=isxfunc_createcustompage) to create custom dialogs, but I agree that it looks like it's way more trouble than it's worth. Updating to remove styling.

**Comment by mrpau-julius** [comment]
@indirectlylit, yes it's possible. Using [custom form](http://www.jrsoftware.org/ishelp/index.php?topic=isxfunc_createcustomform)  and the [classes references](http://www.jrsoftware.org/ishelp/index.php?topic=scriptclasses).

This is my initial output and still work on progress. It takes time to design like this and also it a hard coding.
error_output

**Comment by benjaoming** [comment]
@mrpau-julius that looks nice. Nothing wrong with the mock-up, and I like the copy-paste friendly error message.

With this new error handling, the error handling itself would potentially need error handling, so let's be cautious of the time it takes to implement and if it becomes complex in itself.

**Comment by indirectlylit** [comment]
Looking good @mrpau-julius! No need to bold the labels

**Comment by mrpau-julius** [comment]
Work in progress, Latest output:
latesterrormsgdesign

**Comment by cpauya** [comment]
Related issue/s:
* https://github.com/learningequality/kolibri/issues/3144

**Comment by benjaoming** [comment]
@mrpau-julius looks good and addresses @indirectlylit 's feedback! Looking forward to the implementation :)

**Comment by cpauya** [comment]
Superseded by https://github.com/learningequality/kolibri-installer-windows/pull/108 - @mrpau-julius please use that PR if you have any further changes.

**Pull request closed without merging**
