### PR TITLE
Launch kolibri is not translated.

### LINKED ISSUE #41: 'launch kolibri' is not translated
see:

image

### PR DESCRIPTION
**Pull request by mrpau-richard**
## Summary 
I updated the inno setup isl strings and also update the kolibri Windows installer crowdin.
Here's the [installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMODZ2TWlhUFVyTVk) to test this PR.

## Issue addressed
This fixes #41 

cc/ @radinamatic @indirectlylit

### CODE REVIEW

**Comment by radinamatic** [comment]
@mrpau-dev 

I'm not seeing this string on Crowdin:

fullscreen_19_10_17_12_09

I translated the new strings you uploaded, but that probably means I'll have to wait for the next build to test them, correct?

**Comment by mrpau-richard** [comment]
@radinamatic I already updated the crowdin for that one.

**Comment by radinamatic** [comment]
Great, @mrpau-richard! I translated the remaining strings, could you build a new installer now that everything is (presumably) in Spanish, and I'll test in a Windows with the Spanish language pack tonight?

Thanks!

**Comment by mrpau-richard** [comment]
@radinamatic Let's merge this to fix your comments [here](https://github.com/learningequality/kolibri-installer-windows/pull/46#issuecomment-339694308)

**Pull request merged**
