### PR TITLE
Extract translated InnoSetup Isl to po file

### PR DESCRIPTION
**Pull request by mrpau-richard**
I extracted the translated InnoSetup isl to po file. To upload it at the Crowdin.

REF: https://jrsoftware.org/files/istrans/

cc @radinamatic

### CODE REVIEW

**Comment by mrpau-richard** [comment]
@radinamatic I added the French po file to this PR, please review it.

**Comment by radinamatic** [comment]
Thank you for extracting French too, @mrpau-richard!

The only problem I see now is that the Brazilian Portuguese PO file actually contains the strings in Italian :thinking: 

Could you re-check that? I see the correct PT-BR strings on that repo:
https://raw.githubusercontent.com/jrsoftware/issrc/master/Files/Languages/BrazilianPortuguese.isl

**Comment by mrpau-richard** [comment]
@radinamatic I updated the  Brazilian Portuguese PO file please validate it. Thanks.

**Comment by radinamatic** [comment]
Ok, strings from the official translations for all 3 languages that we can reuse are now correct.

My only doubt remains if we need to commit these files as-is, or we need a more elaborate strategy. 
The way Crowdin works, the PO files for source strings in English are named the same way as the translated ones, correct?

So inside the ``kolibri-installer-windows/src/installer-and-application-po-files/`` folder we will have: 

`innosetup.po`
`kolibri-installer.po`

in English, plus both for each of the languages we currently support. Once all are translated on Crowdin, they need to be pulled into the repo, and the respective `.isl` files built for each of the supported languages. Am I understanding this correctly?

cc @indirectlylit

kolibri-installer-windows/src/inno-compiler/Languages/

**Comment by cpauya** [comment]
For clarity, maybe we rename these files into these?

* `innosetup.po` --> `innosetup-english.po`
* `kolibri-installer.po` --> `innosetup-english-customized-strings.po`

@mrpau-richard will have to modify the `python-scripts/encode-strings.py` script to accept one or more `.po` file/s and merge them together to produce one `.isl` file.

Yes @radinamatic, you are correct.

**Comment by mrpau-richard** [comment]
@radinamatic I forgot that we have modified strings at the `innosetup.po` I need to move it at our custom po file. don't upload it yet at the CrowdIn.

**Comment by mrpau-richard** [comment]
@radinamatic I finished moving those modified strings from `innosetup.po` and I also renamed the `PO` files as @cpauya comment above. 

The `innosetup-english.po ` and `innosetup-english-customized-strings.po` files are ready to upload at the Crowdin.

**Comment by indirectlylit** [comment]
let's merge this in.

please double-check milestone and target branch before merging, though

**Comment by indirectlylit** [comment]
cc @mrpau-dev

**Comment by indirectlylit** [comment]
I'm confused about the milestones and tags: I see the 1.4.0 milestone was closed, but I don't think it was ever released?

**Comment by cpauya** [comment]
> I'm confused about the milestones and tags: I see the 1.4.0 milestone was closed, but I don't think it was ever released?

Not sure what happened here too.  It shouldn't be closed as we have to release yet.  There's a beta1 for 1.4.0 at https://github.com/learningequality/kolibri-installer-windows/releases/tag/v1.4.0-beta1 

Any ideas @mrpau-richard?

**Comment by mrpau-richard** [comment]
My fault, I closed it because there's no remaining issues for that milestone. 
I should wait until the `1.4.0` is released before closing the milestone., noted this.

**Pull request merged**
