### PR TITLE
Update Kolibri on the Web links

### LINKED ISSUE #28: Update "Kolibri on the Web" links
installation step 10 todo change link for kolibri on the web

Currently takes you to https://learningequality.org/

Maybe it should point to https://community.learningequality.org/c/kolibri ?

### PR DESCRIPTION
**Pull request by mrpau-richard**
Add another Kolibri support web links.

here's the installer to test this https://drive.google.com/open?id=1cXHK7i2b1lMhkcpUj8hNeyHaEng-xl22

This fixes #28 

/cc @radinamatic @indirectlylit

### CODE REVIEW

**Comment by radinamatic** [comment]
@mrpau-richard Links work a-OK! :+1: 

win10 start running - oracle vm virtualbox_113

I was thinking of updating the wording though... Maybe "Kolibri Website" or "Kolibri Homepage" for the first, and "Community Forums Support" for the second. @indirectlylit?

**Comment by indirectlylit** [comment]
First a question: since these links are in a "Kolibri" group, is it redundant to include the term 'Kolibri' in the item names? I.e. should we do "Uninstall Kolibri" or just "Uninstall"?

I'd recommend maybe having three links...

| String | URL |
|--|--|
| Homepage | `https://learningequality.org/kolibri/` |
| Documentation | `https://kolibri.readthedocs.io` |
| Community forums | `https://community.learningequality.org/` |

thoughts?

**Comment by mrpau-richard** [comment]
>First a question: since these links are in a "Kolibri" group, is it redundant to include the term 'Kolibri' in the item names? I.e. should we do "Uninstall Kolibri" or just "Uninstall"?

@indirectlylit I think we should use the `Uninstall Kolibri`. The Python installer use the same name on their installer.
screen shot 2018-04-24 at 4 38 00 pm

@radinamatic Here's newly built [installer](https://drive.google.com/open?id=1fuD34U2Z7d6qOcRwBDo_31o72ay7zt71) for the changes that @indirectlylit suggested.

**Comment by indirectlylit** [comment]
Cool! the only questions I have are:

* https://learningequality.org/kolibri/ or  https://learningequality.org/
* https://community.learningequality.org/ or https://community.learningequality.org/c/support/kolibri

Thoughts?

**Comment by radinamatic** [comment]
@indirectlylit I agree with your point about repetitive "Kolibri" inside the group option, but after checking other programs in Windows, they do seem to favor the redundancy:

screenshot - 30-apr-18 9_37_28 am

screenshot - 30-apr-18 9_40_01 am

However, I don't have a strong opinion, and would agree we keep it simple! :slightly_smiling_face: 
On your second suggestion, I'd prefer the links to be as specific as possible (Kolibri page, and Kolibri category on the community forums). 

@mrpau-richard The Start menu for the latest installer looks good, the only suggestion I would have is to maybe change the order...? 

| String | URL |
|--|--|
| Kolibri | (start server - no URL) |
| Documentation | `https://kolibri.readthedocs.io` |
| Community forums | `https://community.learningequality.org/c/support/kolibri` |
| Homepage | `https://learningequality.org/kolibri/` |

As it stands now, starting Kolibri is the last option, and that seems a bit not intuitive to me.

win10 start running - oracle vm virtualbox_122

**Comment by radinamatic** [comment]
And we don't have the `Uninstall` options anymore, wasn't that a new Windows 10 restriction...?
I wonder how Python gets around that... :thinking:

**Comment by mrpau-richard** [comment]
>And we don't have the Uninstall options anymore, wasn't that a new Windows 10 restriction...?
I wonder how Python gets around that... 

It's Windows 10 restriction @radinamatic. I think it's because Python used different compiler.
>@mrpau-richard The Start menu for the latest installer looks good, the only suggestion I would have is to maybe change the order...?

Okay @radinamatic I will change it.

**Comment by mrpau-richard** [comment]
@radinamatic according to this [reference](http://www.jrsoftware.org/iskb.php?startmenuorder) it's difficult and not recommend to set the web links in order to your suggestion.

**Comment by radinamatic** [comment]
@mrpau-richard Ok, it most probably wouldn't be the first time Windows seems unintuitive to me... :unamused: 

Could you build another installer, with those more Kolibri-specific links (even in this "unintuitive" order), for one last round of testing and them we can merge this? Thanks!

**Comment by mrpau-richard** [comment]
@radinamatic you can grab the newly built installer [here](https://drive.google.com/open?id=1Notq6OQ_bP9oagW6dFmdguhw8UrVHb8P)

**Pull request merged**
