### PR TITLE
Kolibri GUI application localisation 

### PR DESCRIPTION
**Pull request by mrpau-richard**
## Summary
Use resource file to localise strings at Kolibri GUI application. 
@radinamatic here's the [installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMdnlBOVNwSmNPams) to test this PR

To test this PR, during the installation select the `spanish`  language, the installer and GUI application will be presented the `spanish` character strings.

## TODO's

- [x] Update the kolibri GUI application strings at crowdin.
- [ ] Create a documentation of how to update the strings from crowdin into Kolibri GUI application.

## issue addressed 
#34 
#29 

cc\ @radinamatic @indirectlylit

### CODE REVIEW

**Comment by radinamatic** [comment]
@mrpau-richard This installer has the same filename `KolibriSetup-0.6.dev020170925003926_git` as the one I tested last week. Is it correct? I'm on limited bandwidth until Thursday so don't want to download and go through testing it if it's not the right one... :slightly_smiling_face:

**Comment by mrpau-richard** [comment]
@radinamatic Yeah, That installer has the same name with the installer built last week. Because I used the same `kolibri whl` file when building that installer.

**Comment by radinamatic** [comment]
@mrpau-richard Thanks, my TIL item :slightly_smiling_face:

**Comment by mrpau-richard** [comment]
@radinamatic here's the [installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMblE3cFU2blhhRjQ) with a localized spanish language from crowdin.

**Comment by radinamatic** [comment]
@mrpau-richard Only including the steps that still need work:

1. Can we try to include the [translated licenses that I listed in this issue](https://github.com/learningequality/kolibri-installer-windows/issues/45)? @indirectlylit do you agree?

msedge - win10 start running - oracle vm virtualbox_012

2. If I recall well, we agreed on skipping this step, that is, not ask any input from the user. Since the desktop shortcut is the only non-command-line means of starting Kolibri, it should be installed always. As it is now, it gets installed regardless of what user does in this step, so we may as well skip asking the user altogether.

msedge - win10 start running - oracle vm virtualbox_015

3. `Launch Kolibri` is still not localized.

msedge - win10 start running - oracle vm virtualbox_018

4. Could we pass the argument that you mentioned in order to enforce the Kolibri setup wizard to start in the language of the installer & OS? As it is now, it still defaults to English.

msedge - win10 start running - oracle vm virtualbox_020

5. Could you build the next installer with the full set of Kolibri `es-es` localized strings? As it is now, half of the interface is still in English, while on Crowdin Spanish stands as 100% approved. 

msedge - win10 start running - oracle vm virtualbox_021
 
6. Task tray options and notifications work well and display in Spanish, good job! :+1:

**Comment by indirectlylit** [comment]
> Can we try to include the translated licenses that I listed in this issue? @indirectlylit do you agree?

I'm not too familiar with translated licenses. I believe for content licenses on Studio, we do _not_ yet internationalize them. I believe it's at least important to ensure that translations are all "official" because it's legal language, so there could be different meanings depending on the translation...

> Could we pass the argument that you mentioned in order to enforce the Kolibri setup wizard to start in the language of the installer & OS? As it is now, it still defaults to English.

This might take a little thought/design - especially if the languages in Kolibri don't match up with the languages in the installer. Filed a kolibri issue here: https://github.com/learningequality/kolibri/issues/2528

**Comment by mrpau-richard** [comment]
@indirectlylit I think we can merge this PR now since @radinamatic already tested this. We just create another issue of what @radinamatic are comments here. So this feature can now available in the latest build.

**Comment by radinamatic** [comment]
Yes, let's merge this already, there don't seem to be anything pending since we cleared up that licenses do not have to be translated (or even there)

I'm yearning to see the improvements when I test the installer! 🙂

**Comment by indirectlylit** [comment]
awesome, nice work!

FYI, if I seem to have missed a notification on github, please prod me on slack :)

**Pull request merged**
