### PR TITLE
develop into master w/ conflicts

### PR DESCRIPTION
**Pull request by benjaoming**
After merging this, we can tag 41373fe on `master` instead of `develop`.

Then, we can tag `f486bb2` as 1.3.4 and bump the version in Kolibri's `release-v0.12.x` so it's already scheduled for 0.12.9.

### CODE REVIEW

**Comment by indirectlylit** [comment]
> develop into master w/ conflicts

What conflicts were resolved? I'd prefer to let @mrpau-dev handle merge conflict since they were the ones writing the code

**Comment by mrpau-richard** [comment]
The conflict is on Spanish `.isl` file @indirectlylit, we will test this today and merge it so we can release the new 1.3.4.

**Comment by mrpau-richard** [comment]
I tested the Spanish language from this PR and it display correctly. Waiting for @mrpau-julius to finish testing before merging this.

**Comment by mrpau-julius** [comment]
The installation looks good, all translated languages are displayed properly. Nothing seems broken.

translated_1

translated_2

translated_3

**Comment by mrpau-richard** [comment]
Thanks @mrpau-julius, merging this.

**Comment by benjaoming** [comment]
@indirectlylit 

> What conflicts were resolved?

That sounded more dramatic than necessary.. the conflicts were of a simple nature: A file got removed in `develop` and changed in `master`, hence there wasn't any line-by-line resolution. I went over the diffs manually WRT the re-introduction of `Spanish.isl` in its new location. There weren't any actual conflicts here.

**Pull request merged**
