### PR TITLE
Generate .po file from kolibri GUI application.

### PR DESCRIPTION
**Pull request by mrpau-richard**
### Summary 

Used [gnu gettext](https://docs.google.com/document/d/1kafEtF68prbCTT0HOTLAf2HvJmH41Kc8R905fWLwsx4/edit) library and [Poedit](https://docs.google.com/document/d/1kafEtF68prbCTT0HOTLAf2HvJmH41Kc8R905fWLwsx4/edit) to generate [`.po`](https://github.com/mrpau/kolibri-installer-windows/blob/feature/generate-po-file-from-kolibri-application/windows/gui-source/Kolibri/po/kolibri-application.po) file from kolibri GUI application.

### Todo
- [x] Create a documentation on how to generate [`.po`](https://github.com/mrpau/kolibri-installer-windows/blob/feature/generate-po-file-from-kolibri-application/windows/gui-source/Kolibri/po/kolibri-application.po) file from the  kolibri GUI application.

cc/ @radinamatic @rtibbles

### CODE REVIEW

**Comment by rtibbles** [comment]
From what I understand here, this makes sense!

**Comment by mrpau-richard** [comment]
Hi @radinamatic I already used the translated po files from the crowdin. you can test it using this [windows installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMcFhfUE85Ri1fT1U).

**Comment by mrpau-richard** [comment]
Hi @radinamatic I noticed that some strings in spanish are not properly displayed, it's same issue in Windows installer I will work on this. 
screen shot 2017-10-09 at 11 30 00 am

**Comment by indirectlylit** [comment]
mind resolving merge conflicts and posting a new installer to test? thanks!

**Comment by mrpau-richard** [comment]
@indirectlylit & @radinamatic this PR is still work in progress. I'm working in translated strings are not properly displayed.

**Comment by mrpau-richard** [comment]
@radinamatic & @indirectlylit i'll create another PR for this. My approach here will work only in ascii character. Here's another [PR](https://github.com/learningequality/kolibri-installer-windows/pull/46). closing this.

**Pull request closed without merging**
