### PR TITLE
Restore the Inno setup Greek isl file

### PR DESCRIPTION
**Pull request by mrpau-julius**
I restore the Inno setup `Greek.isl` file to fix this issue #131

### CODE REVIEW

**Comment by mrpau-julius** [comment]
I create a testing PR in Kolibri repo on this link https://github.com/learningequality/kolibri/pull/5870.
Need a reviewer @mrpau-richard.

**Comment by mrpau-richard** [comment]
I tested this on Windows 10 and the Greek Language strings display correctly.

**Comment by mrpau-julius** [comment]
Thank you @mrpau-richard, please merge this PR.

**Comment by mrpau-richard** [comment]
Also tested this on Windows 7 and Greek strings are properly displayed. merging this now.

**Pull request merged**
