### PR TITLE
Develop -> Master

### PR DESCRIPTION
**Pull request by indirectlylit**

### CODE REVIEW

**Comment by indirectlylit** [comment]
@cpauya @mrpau-dev two small notes on release process:

normally we merge to master before tagging a final build. I'm going to merge this PR, delete the existing tag, and re-tag:

image


Also, generally we delete old pre-releases and only show the most recent:

image

**Comment by indirectlylit** [comment]
nice job maintaining the changelog!

image

**Comment by indirectlylit** [comment]
moved `v1.3.1` tag from 7263b89b32f7800196ec2ad963314e382c664ac6 to a9635571c78aade0493573da9fdd082e1aa62095

**Comment by benjaoming** [comment]
Yes, the change log is super nice! :+1:

**Pull request merged**
